# Generated by Django 3.0.6 on 2020-07-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('Health', 'Health'), ('Tech', 'Tech'), ('Other', 'Other')], max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('fund_need', models.IntegerField()),
                ('fund_raised', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('document', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=12, null=True)),
                ('pan', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=1000)),
                ('modeofpay', models.CharField(choices=[('Wallet', 'Wallet'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI')], max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Business')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
