# Generated by Django 3.0.6 on 2020-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_invest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='2', max_length=13, unique=True, verbose_name='phone'),
        ),
    ]
